### ISSUE TITLE
Blocks don't turn off correctly

### ISSUE THREAD

**Issue by 7studio** [maximebj/advanced-gutenberg-blocks#11]
It seems that when I disable some blocks into the Gutenberg Blocks Settings interface, they aren't disabled in Gutenberg. 

![screenshot](https://user-images.githubusercontent.com/835430/43897322-e254a184-9bdb-11e8-81a7-de203ef4d4d1.png)

Plus, I have a beautiful error in my console:

> Uncaught TypeError: deactivatedBlocks.forEach is not a function at deactivator.build.js?ver=1.3:4

I found this issue because I ran into a problem with my next plugin and I was curious how you achieved that.

To work correctly, you should wrap your code into `window._wpLoadGutenbergEditor.then( function() { } );` and you should add `wp-edit-post` as dependency. See https://github.com/WordPress/gutenberg/issues/4848#issuecomment-388174948

Hope this issue contributes to your plugin :)

**Comment by maximebj** [comment]
Seems to work well Thanks !for your help ! 
I will ship a new version today with some bugfixes
