### ISSUE TITLE
Error on activation

### ISSUE THREAD

**Issue by DannyCooper** [maximebj/advanced-gutenberg-blocks#12]
I'm getting this error on activation:

`Notice: Undefined variable: submenu in /app/public/wp-content/plugins/advanced-gutenberg-blocks/classes/WP/Settings.php on line 71`

**Comment by DannyCooper** [comment]
I think it's because the global $submenu has been commented out, but called referenced here - https://github.com/maximebj/advanced-gutenberg-blocks/blob/14b817aa74b6b4b49e1247f4a9b02d66a04c5dce/classes/WP/Settings.php#L71

**Comment by maximebj** [comment]
Hi, yes that's it, I fixed it few days ago but I didn't push it yet. you can comment line 71 for now and I'll publish a new version soon.

thank you !
