### ISSUE TITLE
[doc] Subhead

### ISSUE THREAD

**Issue by strarsis** [maximebj/advanced-gutenberg-blocks#18]
What is exactly the purpose of the subhead block?
I want to group heading and other heading and/or 
paragraph elements together so I can style them together (e.g. a border).

**Comment by maximebj** [comment]
Hi, 

The subhead was removed from the core so I put it back, it's just meant to to do an introduction, or "chapo" 

For what you need you may check others plugins like Atomic blocks or coblocks, they aim to copy the behavior of page builders
