### ISSUE TITLE
readme.txt shows a donate link which does not work

### ISSUE THREAD

**Issue by Theremingenieur** [maximebj/advanced-gutenberg-blocks#19]
Please fix the donate link, so that people can donate ;) 
<img width="1552" alt="capture d ecran 2018-12-06 a 10 51 40" src="https://user-images.githubusercontent.com/25463159/49576249-f8ad4f00-f944-11e8-9c56-3ff30878e3bc.png">

**Comment by maximebj** [comment]
Oh the website is down, thanks ! 

I'll upgrade to my direct paypal link here: https://paypal.me/maximebj 

Thank you
