### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by franco27** [maximebj/advanced-gutenberg-blocks#22]
hello

setting wordpress 5.0.1 : PHP 7.2 - MYSQL v.5.5 / host at OVH

I can't activate your extension because there is this error message:
"The extension could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected 'LIST' (T_LIST), expecting identifier (T_STRING) in /home/denalogi/www/wp-content/plugins/advanced-gutenberg-blocks/classes/Helpers/Dashicons.php on line 23"

Thank you for helping me
francois

**Comment by franco27** [comment]
Installing from WordPress and not from github file

**Comment by maximebj** [comment]
Is it still the case with version 1.6 just released today?

**Comment by franco27** [comment]
With version 14.4 and 15, there is a problem with activation. Version 16, I do not know I have to try.
Currently I can not test. I send you an answer

**Comment by maximebj** [comment]
I can't reproduce it right now. That's weird. 

But if you are in PHP 7.2 there should'nt be any issue though...

**Comment by franco27** [comment]
When I test, I will confirm that this problem is solved or not solved. Thanks a lot for your answers.

**Comment by franco27** [comment]
No, sorry, my problem is still not solved.

**Comment by franco27** [comment]
I updated via WordPress and then clicked to activate it.    I always get the same error message. 
 


A 2nd attempt, I uninstalled and reinstalled your extension and still have problems to activate it. 
 
With WordPress 5, I don't need to install the Gutenberg extension to activate your extension.  Can you confirm that?    Thanks again for your help.

**Comment by maximebj** [comment]
Yes it works with WP 5.0 naturally.

A friend of mien got the same issue, I'm still investigating to find where it comes from.

**Comment by maximebj** [comment]
Ok It may be a reserved keyword. 

Can you test a little thing for me? 

Change : 

LIST to LISTE in WP/Classes/Helpers/Dashicons on line 23
and
Dashicons::LIST to Dashicons::LISTE in WP/Classes/Services/Blocks.php on line 162

And tell me if the issue is still around

**Comment by franco27** [comment]
Sorry I ran out of free time. 

I thank you again and confirm that this problem has been resolved

**Comment by maximebj** [comment]
Thanks!
