### ISSUE TITLE
make this available for native code block

### ISSUE THREAD

**Issue by jmau111** [maximebj/advanced-gutenberg-blocks#24]
Hi,

thanks for the great work, the code block is pretty cool. Is it possible to extend it to the native code block so the existing code snippets would be highlighted ?

**Comment by maximebj** [comment]
I was thinking about it but I prefered make a new block. 

But may be if I apply themes to the native code block, it should work.

For now it's impossible, in Gutenberg, to make changes in native blocks, that's why I've created mine

**Comment by maximebj** [comment]
I think I can extend it (as you told me on slack, you found a guy doing it). It's on my idea lists for later.
