### ISSUE TITLE
code preview only displays html

### ISSUE THREAD

**Issue by didier-v** [maximebj/advanced-gutenberg-blocks#25]
Whatever the selected language, the preview uses html to display the code:
[screenshot of the editor](https://i.imgur.com/okQqqEm.png)
[screenshot of the preview](https://i.imgur.com/SVnS3I1.png)

**Comment by maximebj** [comment]
This is indeed weird. 

I can't reproduce the bug. Do you have a page online where I can check this? 

Can you open the browser console and tell me if you see a JS error.

**Comment by didier-v** [comment]
There is no JS error, but I found the line that causes the bug. 
in `advanced-gutenberg-blocks/classes/Blocks/Code.php` , line 248

`		$key = array_search( $attributes['language'], array_column( $languages, 'slug' ) );
`

**Comment by maximebj** [comment]
Do you use the filter to add your own language somewhere ? Maybe you forgot to return the array at the end of the function?

**Comment by didier-v** [comment]
I didn't add any language. I only use the ones provided by Code Mirror.

I replaced array_column with a call to custom function:
`public function get_slugs($languages) {`
`  $slugs = [];`
`  foreach ($languages as $language) {`
`     $slugs[]=$language['slug'];`
` }`
` return $slugs;`
`}`

With that fix the language is now displayed in the header of the block and some languages are rendered correctly (html, css, js).
Others are not (Python, swift, java...).

**Comment by maximebj** [comment]
Can you turn the editor in code mode and copy paste me the Code blocks HTML generated please?

You should have this: 

`





` 

I've tried exactly the same example but it seems to work. 

Did you try to update to 1.8.4 ? The issue is still here ?

**Comment by maximebj** [comment]
Also, you can try to `var_dump($this->get_language_list());` on line 248, and also `var_dump($key);`

**Comment by didier-v** [comment]
My version is 1.8.4
I did tests with Safari and Chrome.
Here is what happens when I turn into code mode: 
![code block test](https://quatrecentscodes.com/images/code-block-test.gif)

Here are the var_dumps for a test with PHP selected.

$this->get_language_list()
array(21) { [0]=> array(3) { ["slug"]=> string(4) "html" ["mode"]=> string(3) "xml" ["label"]=> string(4) "HTML" } [1]=> array(3) { ["slug"]=> string(3) "css" ["mode"]=> string(3) "css" ["label"]=> string(3) "CSS" } [2]=> array(3) { ["slug"]=> string(3) "php" ["mode"]=> string(3) "php" ["label"]=> string(3) "PHP" } [3]=> array(3) { ["slug"]=> string(2) "js" ["mode"]=> string(10) "javascript" ["label"]=> string(2) "JS" } [4]=> array(3) { ["slug"]=> string(3) "jsx" ["mode"]=> string(3) "jsx" ["label"]=> string(3) "JSX" } [5]=> array(3) { ["slug"]=> string(3) "xml" ["mode"]=> string(3) "xml" ["label"]=> string(3) "XML" } [6]=> array(3) { ["slug"]=> string(4) "sass" ["mode"]=> string(4) "sass" ["label"]=> string(4) "Sass" } [7]=> array(3) { ["slug"]=> string(6) "stylus" ["mode"]=> string(6) "stylus" ["label"]=> string(6) "Stylus" } [8]=> array(3) { ["slug"]=> string(6) "python" ["mode"]=> string(6) "python" ["label"]=> string(6) "Python" } [9]=> array(3) { ["slug"]=> string(2) "go" ["mode"]=> string(2) "go" ["label"]=> string(2) "Go" } [10]=> array(3) { ["slug"]=> string(4) "ruby" ["mode"]=> string(4) "ruby" ["label"]=> string(4) "Ruby" } [11]=> array(3) { ["slug"]=> string(4) "java" ["mode"]=> string(5) "clike" ["label"]=> string(4) "Java" } [12]=> array(3) { ["slug"]=> string(1) "c" ["mode"]=> string(5) "clike" ["label"]=> string(1) "C" } [13]=> array(3) { ["slug"]=> string(3) "c++" ["mode"]=> string(5) "clike" ["label"]=> string(3) "C++" } [14]=> array(3) { ["slug"]=> string(2) "c#" ["mode"]=> string(5) "clike" ["label"]=> string(2) "C#" } [15]=> array(3) { ["slug"]=> string(11) "objective-c" ["mode"]=> string(5) "clike" ["label"]=> string(11) "Objective C" } [16]=> array(3) { ["slug"]=> string(5) "swift" ["mode"]=> string(5) "swift" ["label"]=> string(5) "Swift" } [17]=> array(3) { ["slug"]=> string(4) "twig" ["mode"]=> string(4) "twig" ["label"]=> string(4) "Twig" } [18]=> array(3) { ["slug"]=> string(6) "django" ["mode"]=> string(6) "django" ["label"]=> string(6) "Django" } [19]=> array(3) { ["slug"]=> string(5) "shell" ["mode"]=> string(5) "shell" ["label"]=> string(5) "Shell" } [20]=> array(3) { ["slug"]=> string(5) "plain" ["mode"]=> string(0) "" ["label"]=> string(10) "Plain Text" } }

$key
int(2)

**Comment by didier-v** [comment]
I could finally update the php version of my server to 7.3. The code blocks render correctly now. 
It just means that this plugin is not compatible with php 7.0.x. 
The html view in the editor is still empty, but the original issue is solved. Thank you.

**Comment by maximebj** [comment]
Thanks a lot for your help. 

So I'm using a function that was not compatible prior to 7.1 or 7.2. I'll try to write a more retro-compatible code for my next release. Thanks again
