### ISSUE TITLE
Post block has a rendering error

### ISSUE THREAD

**Issue by Theremingenieur** [maximebj/advanced-gutenberg-blocks#3]
When adding the single post block in the Gutenberg editor, everything is fine. But when viewing the page containing this post block, the post title appears unfiltered, displaying as  [:en]New in 2018[:fr]Nouveau en 2018[:de]Neu in 2018[:] - obviously not going through the WP multilang filter. In opposite, the default Wordpress category block renders (and translates) post titles correctly...

**Comment by maximebj** [comment]
For now there is some kind of performance issues and bugs when using a loop inside Gutenberg. 

Sometimes it fires a memory error, and other times it goes on an infinite loop. So for now I'm obliged to "cheat" a little and call directly post->title and $post->excerpt unfiletered

Issue is referenced here for now : https://github.com/WordPress/gutenberg/issues/5572 

I hope I will be able soon to find a solution to make it clean

**Comment by Theremingenieur** [comment]
Thank you for writing back on that. I wonder how this is done in the default Wordpress category block, where the post titles render obviously without problems. Perhaps, you might find some inspiration there?

I will be patient in the meantime and appreciate your Google maps block which works very well!

**Comment by Theremingenieur** [comment]
Any news on this?

**Comment by maximebj** [comment]
I can't do anything until the bug is fixed in the Gutenberg Core but I'll take a look to find a workaround

**Comment by maximebj** [comment]
I'm sorry than it's taking some time to fix my bugs buy I launched AGB as a side project. For now I'm writing a course series about Gutenberg Development at https://capitainewp.io and must deliver it for this month. 

I'll get back to this plugin in a few weeks

**Comment by Theremingenieur** [comment]
I'd suggest you have a look onto the "Caxton Blocks" plugin for inspiration. They have a nice post grid block which works well.

**Comment by Theremingenieur** [comment]
We are the next month, now... ;)

**Comment by Theremingenieur** [comment]
All I wanted was that the blocks which you published already work correctly as you described. Unfortunately, they simply don’t. I didn’t ask for a new creation, but only for your already existing blocks just working and meeting the specifications which you defined and published. I understand now that we have different ethics. For me, paid or not, stuff which I publish must work at 100% - question of honor. I can’t sleep well as long as there are unresolved issues. Other people might think differently.

**Comment by maximebj** [comment]
I've looked at Caxton Blocks but their approach is not really the cleanest way. 

I'm still looking for a workaround waiting for Gutenberg to fix the issue

**Comment by maximebj** [comment]
Ok fixed with a standard WP_Query and reset_post_data instead of get_post() 

(Theorically it's the same thing but somewhere, something happens) 

Will be fixed in the next release 1.2

cc: @Theremingenieur thanks for your patience. 
Since Gutenberg 2.8 brings a lot of new stuff, I had to rewrite a lot of things in the plugin. took me time + writing my Gutenberg Courses

**Comment by Theremingenieur** [comment]
Thank you for your efforts! The Post block is working well on my website which allowed me to uninstall the Caxton stuff for now. In terms of website performance and easy maintenance, I always prefer having only the strict necessary minimum of plugins running...

**Comment by maximebj** [comment]
You're welcome! 

Yeah I like running my websites with the fewest plugins possible too.

I'll add soon a posts grid + products grids blocks (even if WooCommerce already has a products grid)

**Comment by Theremingenieur** [comment]
Actually reworking one of my websites and could use a post grid, now... Did you already find time to move on with that?

**Comment by Theremingenieur** [comment]
Looking forward to that à la rentrée ;) 

Bonnes vacances !
