### ISSUE TITLE
How to contribute in the project?

### ISSUE THREAD

**Issue by AndreaBarghigiani** [maximebj/advanced-gutenberg-blocks#30]
Hi @maximebj,
first and foremost congrats for the great work you're doing here. I tested your project few months ago but at the end I chosed to use the Atomic Blocks plugin because it has more _marketing related_ blocks like CTA block and others.

Anyway I start using it but I didn't like it much because I had a feeling of "closed source".

You instead propose to contribute to the project right from the homepage and since I [had my take](https://github.com/skillsAndMore/sam-gutenberg) on building blocks for fun I would like to contribute to the project because I do not think that the WordPress ecosystem needs another Gutenberg blocks bundle plugin (nor I think to have all the time needed to take care of a full project).

I saw the continuous work and improvement you've done here and I would like to know if is possible (and how) contribute to this project.

I have few ideas for next blocks and I think that this could a great opportunity for myself to learn something and partecipate in growing a really good project but since I didn't find any Contribute.md and I am not so active on Twitter I thought that open an issue could be a nice way to make contact. 

All the best.

**Comment by maximebj** [comment]
Hi, thanks for the message! 
I'm sending you an e-mail to talk with you about this! 
I would love some help but still need to find a way to AGB (will it be another all-in-one blocks, or a specific plugin with really original and new blocks?)
