### ISSUE TITLE
Second Recent Posts block added to page won't render

### ISSUE THREAD

**Issue by Josefism** [maximebj/advanced-gutenberg-blocks#31]
My client's website at [https://www.laureloakinn.com/location/](https://www.laureloakinn.com/location/) allows me to add two recent post blocks in the backend, but only the first one is rendered in the frontend. I am attempting to use one for category "Restaurants" and the second for category "Attractions". 

Any advice on how to accomplish two recent post blocks on the same page would be most appreciated.

**Comment by maximebj** [comment]
Hi ! It seems to be a bug, I'll look into that quickly !

**Comment by maximebj** [comment]
"Quickly"... 

I've tried on my latest version but it seems to work fine. It may be fixed in recent updates. Feel free to open if you experience this issue again
