### ISSUE TITLE
Expired SSL on advanced-gutenberg-blocks.com

### ISSUE THREAD

**Issue by Bilal-io** [maximebj/advanced-gutenberg-blocks#32]
Please check the website: https://advanced-gutenberg-blocks.com
The SSL has expired on the 20th of February.
If possible, use https://certbot.eff.org/ to automatically renew the certificate.

**Comment by maximebj** [comment]
Thanks ! My friend host it but the auto renewal always fails ^^' I'll fix that, thanks !
