### ISSUE TITLE
Code block - Undefined post_id when WP_DEBUG true

### ISSUE THREAD

**Issue by bobbingwide** [maximebj/advanced-gutenberg-blocks#33]
Notice: Undefined variable: post_id in /home/bworguk/public_html/wp-content/plugins/advanced-gutenberg-blocks/classes/Blocks/Code.php on line 103

**Comment by maximebj** [comment]
Thanks ! I've removed the useless var
the code still worked because if we don't provide an id, the current one is selected.

Fix in the next release
