### ISSUE TITLE
gmap block not displaying in front end

### ISSUE THREAD

**Issue by bobbingwide** [maximebj/advanced-gutenberg-blocks#34]
I'm creating a catalogue of blocks. The Google Map is not appearing in the front-end

https://blocks.wp.a2z/block/google-map-advanced-gutenberg-blocks-gmap/

It looks like wpautop has been run against the generated JavaScript.

![image](https://user-images.githubusercontent.com/2474435/56052019-5238e680-5d48-11e9-90d0-e1f98ceb71ba.png)

I'll investigate further.

**Comment by bobbingwide** [comment]
I've confirmed that the problem was associated with wpautop being run after the block had been rendered. Having disabled this logic, which was part of one of my plugins, the block now displays correctly.

**Comment by maximebj** [comment]
Ok Good to know ! 
I've already seen that once.
If wpautop is launched to late, it replaces everything. Maybe a more selective approach (when the blocks are parsed for example, and wpautop only a specific list of content...)
