### ISSUE TITLE
WordPress plugin card block : can't select plugin

### ISSUE THREAD

**Issue by Dezodev** [maximebj/advanced-gutenberg-blocks#35]
Hi,

I just started a site with your plugin.

I wanted to use the plugin card block. I searched for the name of a plugin but the results of the search is not displayed correctly. You can see it in the picture below.

![2019-05-10_190312_dezodev tk](https://user-images.githubusercontent.com/13338419/57544105-a7bbdf80-7356-11e9-9858-df73ec05e79e.png)

When I click on one of the plugins, nothing happens next.

Do you have a solution to correct this?

Thanks in advance,
Deniz.

**Comment by maximebj** [comment]
thanks for reporting this. 

Have you tried with another query, like Yoast for example ? What is the version of your WordPress site ? 
(I didn't check for the latest 5.2, or maybe there was a change in the wp.org API)

**Comment by Dezodev** [comment]
I tried with other search terms (yoast, seo and others) but I have the same result.

I put you below the info of my WordPress that can help you.

`
### wp-core ###

version: 5.2
site_language: fr_FR
user_language: fr_FR
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-themes (2) ###

Tabor: version: 1.6.15, author: ThemeBeans
Twenty Nineteen: version: 1.4, author: L’équipe WordPress

### wp-plugins-active (8) ###

Advanced Gutenberg Blocks: version: 1.9.1, author: maximebj
Akismet Anti-Spam: version: 4.1.1, author: Automattic
Block Gallery: version: 1.1.6, author: Rich Tabor
CoBlocks: version: 1.9.4, author: CoBlocks
Contact Form 7: version: 5.1.1, author: Takayuki Miyoshi
Dezo Tools: version: 0.2.0, author: Dezodev
Gutenberg Blocks for Tabor: version: 1.0.4, author: ThemeBeans
The SEO Framework: version: 3.2.4, author: Sybre Waaijer

### wp-server ###

server_architecture: Linux 3.10.0-714.10.2.lve1.5.17.1.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.1.29 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_size: 128M
php_post_max_size: 128M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: false
htaccess_extra_rules: false

`

**Comment by maximebj** [comment]
Hey ! I've found the Bug. 

In fact the WordPress Plugin API sometimes returns an array, and sometimes an object, and deal with it. So I added some code to avoid any issues.

Thanks ! Update is on its way
