### ISSUE TITLE
Website Card Preview

### ISSUE THREAD

**Issue by sebastienserre** [maximebj/advanced-gutenberg-blocks#36]
Hello Maxime,
Your block "Website Card Preview" doesn't include `src` in the `img` markup. :-(

**Comment by maximebj** [comment]
Sometimes it doesn't find the image. Using opengraph API I don't receive everytime the same datas so I must try several cases. Can you provide me the URL you try to preview, so I can try on my site and see what are the returned datas?

**Comment by sebastienserre** [comment]
Hello Maxime,
Example, Itry to have a preview of https://thivinfo.com/blog/contribuer-au-projet-wordpress-quand-on-est-pas-developpeur-cest-possible/
It makes me in front:
![front](https://i.imgur.com/uqZoSm2.png)
(I think only the white one should be great)
and in back:
![back](https://i.imgur.com/Y7DVXUD.png)

**Comment by maximebj** [comment]
Fixed in 1.9.2
