### ISSUE TITLE
Post block - Undefined variable when WP_DEBUG true and author toggle selected 

### ISSUE THREAD

**Issue by bobbingwide** [maximebj/advanced-gutenberg-blocks#39]
When displaying a Post block on the front end a couple of Notices are displayed when WP_DEBUG is true and the Display author toggle is selected.

![CED8D325-A72E-40E3-BB65-0A63169F55A3](https://user-images.githubusercontent.com/2474435/60247124-f518ef80-98b7-11e9-8c67-1d8275fd9387.png)

**Comment by maximebj** [comment]
Thanks, I'll check that soon!

**Comment by bobbingwide** [comment]
PS. Did you see my tweet about getting 404’s when trying to view a particular block on your website? Ah, yes, you must have done.. they’re working now!
