### ISSUE TITLE
Currency position does not reflect WooCommerce option

### ISSUE THREAD

**Issue by bobbingwide** [maximebj/advanced-gutenberg-blocks#40]
In the addtocart and product blocks the position of the currency symbol depends on whether or not it’s a dollar ( $ ). It would be better if the logic was consistent with WooCommerce, using the currency position.
![64D2674D-6C34-4872-8311-48285278BC7F](https://user-images.githubusercontent.com/2474435/60703468-c45d3980-9ef9-11e9-8a09-c593dcdbfcd2.png)

**Comment by maximebj** [comment]
Hi, it's a good idea and would be a good practice indeed. It's on my feature list now. Thanks
