### ISSUE TITLE
Code block doesn't display correctly on frontend

### ISSUE THREAD

**Issue by itanea** [maximebj/advanced-gutenberg-blocks#41]
This is what I have in frontend when I use code blocks of your plugin :

![image](https://user-images.githubusercontent.com/425998/62275635-a6282200-b442-11e9-9fa6-e642d9582d6e.png)

Can you help please ?

**Comment by itanea** [comment]
I have these errors in console. Hope it helps :

![image](https://user-images.githubusercontent.com/425998/62277218-fbb1fe00-b445-11e9-9d14-fb00ae8d217b.png)

**Comment by itanea** [comment]
La purge de tous les caches n'a pas aidé non plus.

**Comment by maximebj** [comment]
Je ne suis pas certain que ça marche dans la preview : les scripts ne sont chargés que sur le site si un bloc est détecté. Si tu publies l'article et que tu vas le visiter pour de vrai, est-ce que ça marche ? 

Sinon vérifie qu'il n'y a pas une erreur qui intervient avant la fin de la page et qui empeche le wp_footer() de s'exécuter en cas.

**Comment by itanea** [comment]
Alors en fait cela ne marche ni à l'édition, ni à l'affichage de l'article publié.

**Comment by itanea** [comment]
Les erreurs remontées sont celles que j'ai envoyé un peu plus haut et provenant de la console du navigateur.
Merci pour ton aide.

**Comment by maximebj** [comment]
Tu as pu essayer sur un autre site ? Je n'ai pas pu reproduire l'erreur et d'autres personnes non plus, je penche du coup pour un souci inhérent au site sur lequel tu es. Je ferme l'issue mais n'hésite pas à la rouvrir en cas
