### ISSUE TITLE
Post block "forgets" the link url to the post

### ISSUE THREAD

**Issue by Theremingenieur** [maximebj/advanced-gutenberg-blocks#5]
Title says it all...

In the editor (admin), the single post block renders well and the url to the post is there.

In the front view, the block renders still nice, but the href tag behind is empty.

**Comment by Theremingenieur** [comment]
Found a fix: In classes/Blocks/Post.php a line is missing.
add 
`$link = get_the_permalink;`
before 			
```
// Get template
			include Consts::get_path() . 'public/templates/post.php';```

**Comment by maximebj** [comment]
I've forgotten to update this when I switched to a standard WP Query + loop. 

I've updated public/templates/post.php and replaced echo $link bt the_permalink(); 

I'll ship it in the next release, meanwhile you can use your trick :) 

Thanks!
