### ISSUE TITLE
Plugin is deactivated and can't be activated again after Gutenberg 2.9.0 update

### ISSUE THREAD

**Issue by Theremingenieur** [maximebj/advanced-gutenberg-blocks#6]
This happens when I try to activate the plugin:
`Fatal error: Uncaught Error: Call to a member function set_block() on null in /home/u210965614/public_html/wp-content/plugins/advanced-gutenberg-blocks/classes/Helpers/Extend.php:47 Stack trace: #0 /home/u210965614/public_html/wp-content/plugins/advanced-gutenberg-blocks/classes/Blocks/Plugin.php(26): AdvancedGutenbergBlocks\Helpers\Extend::register_block('advanced-gutenb...', 'WordPress Plugi...', Array) #1 /home/u210965614/public_html/wp-content/plugins/advanced-gutenberg-blocks/classes/AdvancedGutenbergBlocks.php(95): AdvancedGutenbergBlocks\Blocks\Plugin->run() #2 /home/u210965614/public_html/wp-content/plugins/advanced-gutenberg-blocks/plugin.php(23): AdvancedGutenbergBlocks\AdvancedGutenbergBlocks->run() #3 /home/u210965614/public_html/wp-admin/includes/plugin.php(1897): include('/home/u21096561...') #4 /home/u210965614/public_html/wp-admin/plugins.php(172): plugin_sandbox_scrape('advanced-gutenb...') #5 {main} thrown in /home/u210965614/public_html/wp-content/plugins/advanced-gutenberg-blocks/classes/Helpers/Extend.php on line 47`

**Comment by maximebj** [comment]
Thanks you I missed that. 

I'll fix this tomorrow and I'll take the necessary steps to get compatible with 2.9 because some libraries has changed name and break compatibility.

**Comment by Theremingenieur** [comment]
Thank you for your reactivity! Looking forward to make temporarily hidden content appear again.

**Comment by maximebj** [comment]
Ok I've found the bug. (the bugs to be fair) 

I'll release Advanced Gutenberg Blocks 1.2.4 this morning, this will require Gutenberg 2.9 from now

thank you for your help

**Comment by Theremingenieur** [comment]
Updated. All problems seem to be fixed. Thank you for the quick fix!

**Comment by maximebj** [comment]
You're welcome ! :) Thanks for helping !
