### ISSUE TITLE
v1.2.7 creates many 404 errors in the background

### ISSUE THREAD

**Issue by Theremingenieur** [maximebj/advanced-gutenberg-blocks#9]
![7cb64222-533d-45be-885f-3e029890bbee](https://user-images.githubusercontent.com/25463159/42123052-aac41e3e-7c4b-11e8-91d9-43e282a903b3.png)

**Comment by maximebj** [comment]
It seems than I call a file which do not longer exists on the project.

And I don't remember its purpose. So I'll remove the call on classes/WP/Gutenberg.php:L78 for the next release !

Thanks !

**Comment by Theremingenieur** [comment]
Merci for your quick reply! I commented that function call out and everything seems to be fine.
